### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by RRz1980** [schreibfaul1/ESP32-A2DP-Source#1]
Hello,

I tried to conect it to the"Jabra SPEAK 510 USB". No sound. I checked, "parseWAV" works well and the program runs with no problem no error message.
There is no connection to the Jabra device. The name of the Jabra device hat some spaces, could it be the reason for not connecting?
An alternative would be to send the data to my smart phone and from that for the Jabra device?

Thanks!

**Comment by schreibfaul1** [comment]
Hi,
I can't say exactly, I don't have a BT device with spaces in the name. Is your device found in the scan? For me this is displayed:
_[I][a2dp_source.cpp:209] filter_inquiry_scan_result(): Scanned device: 41:42:3e:24:38:ea  --Class of Device: 0x240418, --RSSI -74, --Manhattan-165327
Manhattan-165327 is my BT device name. And the name must be entered in BT_SINK_NAME
