### ISSUE TITLE
I2S microphone as source of data

### ISSUE THREAD

**Issue by rmond18** [schreibfaul1/ESP32-A2DP-Source#2]
Hi,

Thank you for sharing your work! I'm wondering if this code could also work with I2S microphone as a source of data instead of the wav file from SD card? Can continuous streaming of audio possible with this set-up? I'm having a hard time integrating the microphone with the A2DP source code since I'm quite new to this. Any tips/guide? 

Thank you very much!! 

Warm regards,
rmond

**Comment by schreibfaul1** [comment]
Any source that can generate a constant data stream (44100Hz, pcm 16bit) works.
I have added an example that is certainly not the most elegant solution, but it is suitable as a basis for your own developments.

**Comment by rmond18** [comment]
Hi, I've also just found a [library](https://github.com/pschatzmann/arduino-audio-tools) for this. 

Thank you very much for your example, I really appreciate it! I'll try to implement it also! Stay safe!
