### ISSUE TITLE
Is it possible to use MP3 instead of WAV?

### ISSUE THREAD

**Issue by pablofr918** [schreibfaul1/ESP32-A2DP-Source#3]
I would like to use this with a mp3 file instead of a wav file, but I am not sure if it is possible.

**Comment by schreibfaul1** [comment]
Most BT devices cannot process mp3, they lack the MP3 decoder. The BT stack must also support this.

**Comment by pablofr918** [comment]
Okay thank you!!
I have another question, I am trying to connect to my phone, but nothing happens, so now I am going to try to connect to a BT speaker, because maybe the reason is that my phone is not a speaker. So:
- The function a2dp_source_init(BT_SINK_NAME, BT_SINK_PIN) will make the connection, and
- The function parseWAV(SPIFFS, "/cello.wav") will reproduce the audio? Or is it needed to call another function to start playing the song?
In my case, I use the SPIFFS system instead of SD, and it compiles, so I guess there is no problem with that.

But I have tried and nothing happens, the name of the BT has spaces, as the other issue created. It makes de parsewav whit no errors, but it does not appear any message of scanning or something like that.

**Comment by schreibfaul1** [comment]
Hello pablofr918,
the name of your BT speaker must be entered in BT_SINK_NAME.  It is not possible to pair with a smartphone, only with pure BT audio device. BT_SINK_PIN and BT_DEVICE_NAME can remain unchanged.
The log looks like this, where 'Manhattan-1665327' is the name of my BT device.
![image](https://user-images.githubusercontent.com/26044260/117440723-b8e35b00-af34-11eb-849f-03ae4b208fd5.png)
The wav file should have a sample rate of 44100 samples/second and 16 bits per sample, SPIFFS will work

**Comment by pablofr918** [comment]
I'm doing it and no connection is made, I'm using BT headphones but when the init() is called, there is no connection between them.

This is the code and the output:

#include "Arduino.h"
#include "a2dp_source.h"
#include "SD.h"
#include "FS.h"
#include <SPIFFS.h>

// Digital I/O used
#define SD_CS          5
#define SPI_MOSI      23
#define SPI_MISO      19
#define SPI_SCK       18

char BT_SINK_NAME[]   = "Beats_Pablo";      // sink devicename
char BT_SINK_PIN[]    = "1234";             // sink pincode
char BT_DEVICE_NAME[] = "ESP_A2DP_SRC";     // source devicename

File            audiofile;    // @suppress("Abstract class cannot be instantiated")

uint32_t        sampleRate;
uint32_t        bitRate;
uint8_t         channels;
uint8_t         bitsPerSample=16;
uint32_t        posDataSection;


//---------------------------------------------------------------------------------------------------------------------
bool parseWAV(fs::FS &fs, String path){
    char chbuf[256];
    File audiofile = fs.open(path.c_str());
    //audiofile=fs.open(path.c_str());
    String afn = (String)audiofile.name();  //audioFileName
    Serial.println(afn);

    if(afn.endsWith(".wav")) {
        audiofile.readBytes(chbuf, 4); // read RIFF tag
        if ((chbuf[0] != 'R') || (chbuf[1] != 'I') || (chbuf[2] != 'F') || (chbuf[3] != 'F')){
            Serial.println("file has no RIFF tag");
            audiofile.seek(0);
            return false;
        }

        audiofile.readBytes(chbuf, 4); // read chunkSize (datalen)
        uint32_t cs = (uint32_t)(chbuf[0] + (chbuf[1] <<8) + (chbuf[2] <<16) + (chbuf[3] <<24) - 8);

        audiofile.readBytes(chbuf, 4); /* read wav-format */ chbuf[5] = 0;
        if ((chbuf[0] != 'W') || (chbuf[1] != 'A') || (chbuf[2] != 'V') || (chbuf[3] != 'E')){
            Serial.println("format tag is not WAVE");
            audiofile.seek(0);
            return false;
        }

        while(true){ // skip wave chunks, seek for fmt element
            audiofile.readBytes(chbuf, 4); /* read wav-format */
            if ((chbuf[0] == 'f') && (chbuf[1] == 'm') && (chbuf[2] == 't')){
                //if(audio_info) audio_info("format tag found");
                break;
            }
        }

        audiofile.readBytes(chbuf, 4); // fmt chunksize
        cs = (uint32_t) (chbuf[0] + (chbuf[1] <<8));
        if(cs>40) return false; //something is wrong
        uint8_t bts=cs-16; // bytes to skip if fmt chunk is >16
        audiofile.readBytes(chbuf, 16);
        uint16_t fc  = (uint16_t)(chbuf[0]  + (chbuf[1] <<8));  // Format code
        uint16_t nic = (uint16_t)(chbuf[2]  + (chbuf[3] <<8));  // Number of interleaved channels
        uint32_t sr  = (uint32_t)(chbuf[4]  + (chbuf[5] <<8) + (chbuf[6]  <<16) + (chbuf[7]  <<24)); // Smpling rate
        uint32_t dr  = (uint32_t)(chbuf[8]  + (chbuf[9] <<8) + (chbuf[10] <<16) + (chbuf[11] <<24)); // Data rate
        uint16_t dbs = (uint16_t)(chbuf[12] + (chbuf[13] <<8));  // Data block size
        uint16_t bps = (uint16_t)(chbuf[14] + (chbuf[15] <<8));  // Bits per sample
        Serial.printf("FormatCode=%u\n", fc);
        Serial.printf("Channel=%u\n", nic);
        Serial.printf("SampleRate=%u\n", sr);
        Serial.printf("DataRate=%u\n", dr);
        Serial.printf("DataBlockSize=%u\n", dbs);
        Serial.printf("BitsPerSample=%u\n", bps);


        if(fc != 1){
            Serial.println("format code is not 1 (PCM)");
            return false;
        }

        if(nic != 1 && nic != 2){
            Serial.print("number of channels must be 1 or 2");
            return false;
        }

        if(bps != 8 && bps !=16){
            Serial.println("bits per sample must be 8 or 16");
            return false;
        }
        bitsPerSample=bps;
        channels = nic;
        sampleRate = sr;
        bitRate = nic * sr * bps;
        Serial.printf("BitRate=%u\n", bitRate);

        audiofile.readBytes(chbuf, bts); // skip to data
        uint32_t s = audiofile.position();
        //here can be extra info, seek for data;
        while(true){
            audiofile.seek(s);
            audiofile.readBytes(chbuf, 4); /* read header signature */
            if ((chbuf[0] == 'd') && (chbuf[1] == 'a') && (chbuf[2] == 't') && (chbuf[3] == 'a')) break;
            s++;
        }

        audiofile.readBytes(chbuf, 4); // read chunkSize (datalen)
        cs = chbuf[0] + (chbuf[1] <<8) + (chbuf[2] <<16) + (chbuf[3] <<24) - 44;
        sprintf(chbuf, "DataLength=%u\n", cs);
        Serial.print(chbuf);
        posDataSection = audiofile.position();
        return true;
    }
    return false;
}

//---------------------------------------------------------------------------------------------------------------------
void setup(){
    Serial.begin(9600);
    SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
    SD.begin(SD_CS);
    SPIFFS.begin();
    if(!SPIFFS.begin()){
        Serial.println("SPIFFS Mount Failed");
        return;
    }
//  Serial.println("AQUI");
    parseWAV(SPIFFS, "/cello.wav");
    Serial.println("debajo");
    a2dp_source_init(BT_SINK_NAME, BT_SINK_PIN);
}
//---------------------------------------------------------------------------------------------------------------------
void loop() {}
//---------------------------------------------------------------------------------------------------------------------
int32_t bt_app_a2d_data_cb(uint8_t *data, int32_t len) // BT data event
{
    if (len < 0 || data == NULL) {
        return 0;
    }
    len = audiofile.read(data, len);
    if(len == 0) audiofile.seek(posDataSection); // EOF? enless loop
    return len;
}

**OUTPUT:**
/cello.wav
FormatCode=1
Channel=1
SampleRate=44100
DataRate=88200
DataBlockSize=2
BitsPerSample=16
BitRate=705600
DataLength=811738
