### ISSUE TITLE
initialize controller failed 259

### ISSUE THREAD

**Issue by andrewstillie** [schreibfaul1/ESP32-A2DP-Source#6]
Unable to get the application to initialise due to the following error message.

14:06:38.777 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
14:06:38.777 -> configsip: 0, SPIWP:0xee
14:06:38.916 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
14:06:38.916 -> mode:DIO, clock div:1
14:06:38.916 -> load:0x3fff0018,len:4
14:06:38.916 -> load:0x3fff001c,len:1044
14:06:38.916 -> load:0x40078000,len:10124
14:06:38.916 -> load:0x40080400,len:5856
14:06:38.916 -> entry 0x400806a8
14:06:39.137 -> [E][a2dp_source.cpp:608] a2dp_source_init(): initialize controller failed 259

Can you offer any help help?

**Comment by schreibfaul1** [comment]
I believe Arduino V1.0.6 is the last version that still works. The newer versions only support BLE.
