### ISSUE TITLE
What is the license for this software?

### ISSUE THREAD

**Issue by elda27** [schreibfaul1/ESP32-A2DP-Source#7]
Thanks for your nice source codes.
But I didn't find this software under any license.
Is it possible to provide license such as OSS license to use for everyone?
Please note that you shouldn't add a license if you don't want to make it available to everyone.

**Comment by schreibfaul1** [comment]
Hello elda27,
this is an example of Espressifs esp-idf, just adapted to the Arduino IDF. I have kept the SW up to date on the different versions. The license is then GPL2.1, which Espressif also uses.
Please note that newer chips like the ESP32-S3 no longer have BT support.

**Comment by elda27** [comment]
Thanks for your reply.
I understand the software license.
